version: '3.9'

services:
  api:
    networks:
      - internal_nw
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - worker
      - beat
    env_file:
      - .env
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: celery -A api.main.celery_app worker --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq-node:5672/
      - CELERY_APP=api.main.celery_app
    networks:
      - internal_nw
    env_file:
      - .env
  beat:
    build:
      context: .
      dockerfile: beat.Dockerfile
    command: celery -A api.main.celery_app beat --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq-node:5672/
      - CELERY_APP=api.main.celery
    env_file:
      - .env
    depends_on:
      - worker
    networks:
      - internal_nw

networks:
  internal_nw:
    external: true